# -*- mode: ruby -*-
# vi: set ft=ruby :

# This gives us the ability of resizing disks from the size put in the Vagrant Box. Some OS may force you to use gparted or similar to really take advantage of the extra space you put here. 
#ENV['VAGRANT_EXPERIMENTAL'] = 'disks'

###################################################################################################
### 					GENERAL CONTROL VARIABLES 				###
###################################################################################################

# Please use only Vagrant Boxes from the Vagrant Cloud that come from trusted or official providers!

## Machine Info:
## -------------

# This base Vagrant box supports VirtualBox, Hyper-V and VMWare Desktop.
BOX_NAME = "hashicorp/bionic64"

# The name of the box that will appear into the GUI 
MACHINE_NAME = "Magic The Hardening"

# The description of the box that will show into the GUI 
MACHINE_DESCRIPTION = "Base Ubuntu Server image, cmd only, maximum hardening"

# Type of OS, needed for some of the Hypervisors
OS_TYPE = "Ubuntu_64"

# This determines the set of customization scripts that will be used
OS_CLASS = "debian"

## Machine Characteristics:
## ------------------------

# In Mb, if you can afford it, more memory is always welcome :). Be careful not to push this too hard, and turn yourself into a Chrome browser :P 
RAM = 2048

# If you can afford it, more cores are always welcome :). Be careful not to push this too hard, and let your host breathe :P
CORES = 2

# Size of the box disk
#DISK_SIZE = "80GB"

# Amount of available VRAM. Consider if your VM is going to have a GUI or not to choose this.
VRAM = 32

# The name of the HD controller greatly varies depending on the box you use
HD_CONTROLLER = "SATA Controller"

## Virtualization parameters:
## --------------------------

# Change to false to run the machine in headless mode (i. e. no VBox Window will be open)
GUI = true

# Audio device, or none for servers
AUDIO = "none"

# Turns on/off 3D acceleration. This does not behave too well on some Linux distros if turned on right now (at least in VirtualBox), so better leave it as you found it! (I tested!). 
VIDEO_3D = "off"

# VirtualBox remote screen
VRDE = "off"

## Provisioning parameters:
## --------------------------

# Type of provisioner. I only use shell provisioners to not requiring installing more software. But this makes it easy to incorporate Ansible, Puppet, Chef or whatever automation you like!
PROVISION_TYPE = "shell"

# Provisioner file extension
PROVISION_FILE_EXTENSION = ".sh"

###################################################################################################
### 				VIRTUAL MACHINE CONFIGURATION 					###
###################################################################################################

Vagrant.configure("2") do |config|
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.
  Vagrant.require_version ">= 2.1.18"

  config.vm.define "ubuntu" do |machine|
    machine.vm.box = BOX_NAME
    machine.vm.network "private_network", ip: "172.17.177.21"
    machine.vm.boot_timeout = 1800 # 30 minutes
    machine.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct: true 

    # This is the VirtualBox VM solution. Use this if you can, as it has more options and optimizations
    machine.vm.provider "virtualbox" do |vb|
      vb.name = MACHINE_NAME  
      vb.memory = RAM
      vb.cpus = CORES
      vb.gui = GUI

      # Base configuration
      vb.customize ["modifyvm", :id, "--audio", AUDIO]        
      vb.customize ["modifyvm", :id, "--clipboard-mode", "bidirectional"]
      vb.customize ["modifyvm", :id, "--description", MACHINE_DESCRIPTION]    
      vb.customize ["modifyvm", :id, "--ostype", OS_TYPE]

      # High-performance configuration: please note that several of these options are not available in the VirtualBox GUI
      # Thus, the performance of this machine should be higher than the ones created via GUI

      # Use VBoxManage to customize the VM for high-performance options and other things
      vb.customize ["modifyvm", :id, "--acpi", "on"]
      vb.customize ["modifyvm", :id, "--accelerate3d", VIDEO_3D]
      vb.customize ["modifyvm", :id, "--apic", "on"]    
      vb.customize ["modifyvm", :id, "--biosapic", "x2apic"]  
      vb.customize ["modifyvm", :id, "--cpu-profile", "host"]
      vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
      vb.customize ["modifyvm", :id, "--hpet", "on"]
      vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
      vb.customize ["modifyvm", :id, "--largepages", "on"]
      vb.customize ["modifyvm", :id, "--longmode", "on"]
      vb.customize ["modifyvm", :id, "--nestedpaging", "on"]            
      vb.customize ["modifyvm", :id, "--pae", "on"]
      # If you have a MAC host and get an error, comment this line, as this feature is not currently supported on MAC (yet)
      vb.customize ["modifyvm", :id, "--pagefusion", "on"]
      vb.customize ["modifyvm", :id, "--rtcuseutc", "on"]
      vb.customize ["modifyvm", :id, "--spec-ctrl", "off"]
      vb.customize ["modifyvm", :id, "--x2apic", "on"]
      vb.customize ["modifyvm", :id, "--vram", VRAM]
      vb.customize ["modifyvm", :id, "--vtxux", "on"]  
      vb.customize ["modifyvm", :id, "--vtxvpid", "on"]		
      vb.customize ["modifyvm", :id, "--vrde", VRDE]	    
      vb.customize ["storagectl", :id, "--name", HD_CONTROLLER, "--hostiocache", "on"]

      # Shared folder (host path, guest path)
      machine.vm.synced_folder "shared", "/host_data"     
    end

    # machine.vm.provision "shell", inline: "export SHELL=/bin/bash"

    # Copy the files required by the Box provisioner
    machine.vm.provision "file", source: "scripts/customization_files/debian_customization", destination: "/home/vagrant/custom_files" 
    machine.vm.provision "file", source: "scripts/customization_scripts/debian_customization", destination: "/home/vagrant/custom_scripts"
    machine.vm.provision "file", source: "scripts/hardened_files/debian_customization", destination: "/home/vagrant/hardened_files"

    machine.vm.provision "shell", inline: "sed -i -e 's/\r$//' /home/vagrant/*/*.sh"
    machine.vm.provision "shell", inline: "sed -i -e 's/\r$//' /home/vagrant/*/*/*.sh"

    # Automatically install software and hardening
    machine.vm.provision "Software Installation (1/2)", type: PROVISION_TYPE, path: "provisioning/" + PROVISION_TYPE + "/provision_install" + PROVISION_FILE_EXTENSION, reboot: true 
    machine.vm.provision "Hardening (2/2)", type: PROVISION_TYPE, path: "provisioning/" + PROVISION_TYPE + "/provision_harden" + PROVISION_FILE_EXTENSION, reboot: true 
  end

  config.vm.define "controller" do |machine|
    machine.vm.box = "ubuntu/trusty64"
    machine.vm.network "private_network", ip: "172.17.177.11"

    machine.vm.provision "file", source: "../../../../../provisioners/ansible/roles/linux", destination: "/vagrant/provisioning/ansible/roles/linux"

    machine.vm.provision "ansible_local" do |ansible|
      ansible.playbook         = "provisioning/ansible/roles/linux/linux_provisioning.yml"
      ansible.verbose          = true
      ansible.install          = true
      ansible.limit            = "nodes" # or only "nodes" group, etc.
      ansible.inventory_path   = "provisioning/ansible/inventory"
      ansible.become           = "yes"
      ansible.version          = "latest"
      ansible.config_file      = "provisioning/ansible/ansible.cfg"
    end
    machine.vm.synced_folder ".", "/vagrant", mount_options: ["umask=077"]
  end


end
