---
# CONTROL PANEL

# Personalization

- name: "CIS,18.1.1.1,CCE-38347-1 | Ensure 'Prevent enabling lock screen camera' is set to 'Enabled'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\Windows\Personalization
     name: "NoLockScreenCamera"
     data: "1" # Enabled
     type: dword
  tags: ['configuration']

- name: "CIS,18.1.1.2,CCE-38348-9 | Ensure 'Prevent enabling lock screen slide show' is set to 'Enabled'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\Windows\Personalization
     name: "NoLockScreenSlideshow"
     data: "1" # Enabled
     type: dword
  tags: ['configuration']

# Regional and Language Options

# Beware that in in older Microsoft Windows Administrative Templates, this setting was initially named 'Allow input personalization'
# The change to 'Allow users to enable online speech recognition services' started with versions Windows 10 R1809 and Server 2019 of the templates
- name: "CIS,18.1.2.2 | Ensure 'Allow users to enable online speech recognition services' is set to 'Disabled'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\InputPersonalization
     name: "AllowInputPersonalization"
     data: "0" # Disabled
     type: dword
  tags: ['configuration']

# MS SECURITY GUIDE

- name: "CIS,18.3.1,CCE-37069-2 | Ensure 'Apply UAC restrictions to local accounts on network logons' is set to 'Enabled'"
  win_regedit:
     path: HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System
     name: "LocalAccountTokenFilterPolicy"
     data: "0" # Enabled
     type: dword
  tags: ['configuration']

- name: "CIS,18.3.3 | Ensure 'Configure SMB v1 server' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\System\CurrentControlSet\Services\LanManServer\Parameters
    name: "SMB1"
    data: "0"
    type: dword
  tags: ['configuration']

# MSS (LEGACY)

- name: "CIS,18.4.1,CCE-37067-6 | Ensure 'MSS: (AutoAdminLogon) Enable Automatic Logon (not recommended)' is set to 'Disabled'"
  win_regedit:
    path: 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon'
    name: "AutoAdminLogon"
    data: "0" # Disabled
    type: string
  tags: ['configuration']

- name: "CIS,18.4.2,CCE-36871-2 | Ensure 'MSS: (DisableIPSourceRouting IPv6) IP source routing protection level (protects against packet spoofing)' is set to 'Enabled: Highest protection, source routing is completely disabled'"
  win_regedit:
     path: HKLM:\System\CurrentControlSet\Services\Tcpip6\Parameters
     name: "DisableIPSourceRouting"
     data: "2" # 'Enabled: Highest protection, source routing is completely disabled'
     type: dword
  tags: ['configuration']

- name: "CIS,18.4.3,CCE-36535-3 | Ensure 'MSS: (DisableIPSourceRouting) IP source routing protection level (protects against packet spoofing)' is set to 'Enabled: Highest protection, source routing is completely disabled'"
  win_regedit:
     path: HKLM:\System\CurrentControlSet\Services\Tcpip\Parameters
     name: "DisableIPSourceRouting"
     data: "2" # 'Enabled: Highest protection, source routing is completely disabled'
     type: dword
  tags: ['configuration']

- name: "CIS,18.4.5,CCE-37988-3 | Ensure 'MSS: (EnableICMPRedirect) Allow ICMP redirects to override OSPF generated routes' is set to 'Disabled'"
  win_regedit:
     path: HKLM:\System\CurrentControlSet\Services\Tcpip\Parameters
     name: "EnableICMPRedirect"
     data: "0" # Disabled
     type: dword
  tags: ['configuration']

- name: "CIS,18.4.7,CCE-36879-5 | Ensure 'MSS: (NoNameReleaseOnDemand) Allow the computer to ignore NetBIOS name release requests except from WINS servers' is set to 'Enabled'"
  win_regedit:
     path: HKLM:\System\CurrentControlSet\Services\NetBT\Parameters
     name: "NoNameReleaseOnDemand"
     data: "1" # Enabled
     type: dword
  tags: ['configuration']

- name: "CIS,18.4.9 | Ensure 'MSS: (SafeDllSearchMode) Enable Safe DLL search mode (recommended)' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\System\CurrentControlSet\Control\Session Manager
    name: "SafeDllSearchMode"
    data: "1" # Enabled
    type: dword
  tags: ['configuration']

- name: "CIS,18.3.10,CCE-37993-3 | Ensure 'MSS: (ScreenSaverGracePeriod) The time in seconds before the screen saver grace period expires (0 recommended)' is set to 'Enabled: 5 or fewer seconds'"
  win_regedit:
     path: HKLM:\Software\Microsoft\Windows Nt\CurrentVersion\Winlogon
     name: "ScreenSaverGracePeriod"
     data: "5"
     type: string
  when: (screensaver_enabled|default(True) == True)
  tags: ['configuration']

- name: "CIS,18.3.13,CCE-36880-3 | Ensure 'MSS: (WarningLevel) Percentage threshold for the security event log at which the system will generate a warning' is set to 'Enabled: 90% or less'"
  win_regedit:
     path: HKLM:\System\CurrentControlSet\Services\Eventlog\Security
     name: "WarningLevel"
     data: "90"
     type: dword
  tags: ['configuration']

# DNS CLIENT

- name: "CIS,18.5.4.2,CCE-Null | Ensure 'Turn off multicast name resolution' is set to 'Enabled'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\Windows NT\DNSClient
     name: "EnableMulticast"
     data: "0" # Enabled
     type: dword
  tags: ['configuration']

# LANMAN WORKSTATION

# By default, for Windows 10 R1703 and older this setting has value 'Enabled'
# Windows 10 R1709 and newer versions have this setting 'Disabled' by default already
- name: "CIS,18.4.8.1,CCE-Null | Ensure 'Enable insecure guest logons' is set to 'Disabled'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\Windows\LanmanWorkstation
     name: "AllowInsecureGuestAuth"
     data: "0" # Disabled
     type: dword
  tags: ['configuration']

# NETWORK CONNECTIONS

- name: "CIS,18.5.11.2,CCE-38002-2 | Ensure 'Prohibit installation and configuration of Network Bridge on your DNS domain network' is set to 'Enabled'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\Windows\Network Connections
     name: "NC_AllowNetBridge_NLA"
     data: "0" # Enabled
     type: dword
  tags: ['configuration']

- name: "CIS,18.5.11.3,CCE-Null | Ensure 'Prohibit use of Internet Connection Sharing on your DNS domain network' is set to 'Enabled'"
  win_regedit:
     path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Network Connections
     name: "NC_ShowSharedAccessUI"
     data: "0" # Enabled
     type: dword
  tags: ['configuration']

- name: "CIS,18.5.11.4,CCE-38188-9 | Ensure 'Require domain users to elevate when setting a network's location' is set to 'Enabled'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\Windows\Network Connections
     name: "NC_StdDomainUserSetLocation"
     data: "1" # Enabled
     type: dword
  tags: ['configuration']

# NETWORK PROVIDER

- name: "CIS,18.5.14.1 | Hardened UNC Paths is set to 'Enabled, with 'Require Mutual Authentication' and 'Require Integrity' set for all NETLOGON shares'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\Windows\NetworkProvider\HardenedPaths
     name: "\\\\*\\NETLOGON"
     data: "RequireMutualAuthentication=1, RequireIntegrity=1"
     type: string
  tags: ['configuration']

- name: "CIS,18.5.14.1 | Hardened UNC Paths is set to 'Enabled, with 'Require Mutual Authentication' and 'Require Integrity' set for all SYSVOL shares'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\Windows\NetworkProvider\HardenedpPaths
     name: "\\\\*\\SYSVOL"
     data: "RequireMutualAuthentication=1, RequireIntegrity=1"
     type: string
  tags: ['configuration']

# REMOTE PROCEDURE CALL

- name: "18.8.37.1,CCE-37346-4 | Ensure 'Enable RPC Endpoint Mapper Client Authentication' is set to 'Enabled'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\Windows Nt\Rpc
     name: "EnableAuthEpResolution"
     data: "1"
     type: dword
  tags: ['configuration']

# WINDOWS COMPONENTS

# AutoPlay Policies
- name: "CIS,18.9.8.1,CCE-37636-8 | Ensure 'Disallow Autoplay for non-volume devices' is set to 'Enabled'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\Windows\Explorer
     name: "NoAutoplayfornonVolume"
     data: "1"
     type: dword
  tags: ['configuration']

- name: "CIS,18.9.8.2,CCE-38217-6 | Ensure 'Set the default behavior for AutoRun' is set to 'Enabled: Do not execute any autorun commands'"
  win_regedit:
     path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer
     name: "NoAutorun"
     data: "1"
     type: dword
  tags: ['configuration']

# This setting has 2 possible values:
#    - 181: CD-ROM and removable media drives
#    - 255: All drives
- name: "CIS,18.9.8.3,CCE-36875-3 | Ensure 'Turn off Autoplay' is set to 'Enabled: All drives'"
  win_regedit:
     path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer
     name: "NoDriveTypeAutoRun"
     data: "255" # All drives
     type: dword
  tags: ['configuration']

# Event Log Service - Application
# Configure System Event Log (Application)
- name: "CIS,18.9.27.1.2 | Ensure 'Application: Specify the maximum log file size (KB)' is set to 'Enabled: 32,768 or greater'"
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\EventLog\Application
    name: "MaxSize"
    data: "1"
    type: dword
  tags: ['configuration']

# Event Log Service - Security
# Configure System Event Log (Security)
- name: "CIS,18.9.27.2.2 | Ensure 'Security: Specify the maximum log file size (KB)' is set to 'Enabled: 196,608 or greater'"
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\EventLog\Security
    name: "MaxSize"
    data: "1"
    type: dword
  tags: ['configuration']

# Event Log Service - Setup
# Configure System Event Log (Setup)
- name: "CIS,18.9.27.3.2 | Ensure 'Setup: Specify the maximum log file size (KB)' is set to 'Enabled: 32,768 or greater'"
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\EventLog\Setup
    name: "MaxSize"
    data: "1"
    type: dword
  tags: ['configuration']

# Event Log Service - System
# Configure System Event Log (System)
- name: "CIS,18.9.27.4.2 | Ensure 'System: Specify the maximum log file size (KB)' is set to 'Enabled: 32,768 or greater'"
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\EventLog\System
    name: "MaxSize"
    data: "1"
    type: dword
  tags: ['configuration']

# OneDrive (formerly SkyDrive)
# This security concern applies to any cloud-based file storage application installed in a workstation
# If your organization has decided to implement OneDrive or other, you'll need to disable this and configure the OneDrive settings using the corresponding template
- name: "CIS,18.9.58.1,CCE-36939-7 | Ensure 'Prevent the usage of OneDrive for file storage' is set to 'Enabled'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\Windows\OneDrive
     name: "DisableFileSyncNGSC"
     data: "1" # Enabled
     type: dword
  tags: ['configuration']

# Remote Desktop Session Host - Security
# Windows Remote Desktop Configured to Always Prompt for Password
- name: "CIS,18.9.65.3.9.1 | Ensure 'Always prompt for password upon connection' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services
    name: "fPromptForPassword"
    data: "1" # Enabled
    type: dword
  tags: ['configuration']
# Strong Encryption for Windows Remote Desktop Required
- name: "CIS,18.9.65.3.9.5 | Ensure 'Set client connection encryption level' is set to 'Enabled: High Level'"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services
    name: "MinEncryptionLevel"
    data: "3" # Enabled: High Level
    type: dword
  tags: ['configuration']

# RSS Feeds

- name: "CIS,18.9.67.5 | Ensure 'Allow indexing of encrypted files' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Search
    name: "AllowIndexingEncryptedStoresOrItems"
    data: "0" # Disabled
    type: dword
  tags: ['configuration']

# Store

# This policy setting only applies to Windows 10 Enterprise and Windows 10 Education editions
# The name of this setting and its values are incorrectly worded
#  - Enabled (1) -> will enable all apps from the Microsoft Store
#  - Disabled (0) -> will disable all apps from the Microsoft Store
# Beware that this policy has a L2 (High Security/Sensitive Data Environment) profile applicability
- name: "CIS,18.9.75.1 | Ensure 'Disable all apps from Microsoft Store' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsStore
    name: "DisableStoreApps"
    data: "0"
    type: dword
  when: (microsoft_store_disabled|default(False) == True)
  tags: ['configuration']

- name: "CIS,18.9.75.3 | Ensure 'Turn off Automatic Download and Install of updates' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsStore
    name: "AutoDownload"
    data: "4" # Disabled; enabled=2
    type: dword
  tags: ['configuration']

- name: "CIS,18.9.75.4 | Ensure 'Turn off the offer to update to the latest version of Windows' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsStore
    name: "DisableOSUpgrade"
    data: "1" # Enabled
    type: dword
  tags: ['configuration']

# This policy setting only applies to Windows 10 Enterprise and Windows 10 Education editions
# Beware that this policy has a L2 (High Security/Sensitive Data Environment) profile applicability
- name: "CIS,18.9.75.5 | Ensure 'Turn off the Store application' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsStore
    name: "RemoveWindowsStore"
    data: "1" # Enabled
    type: dword
  when: (microsoft_store_disabled|default(False) == True)
  tags: ['configuration']

# Windows Defender SmartScreen - Explorer
# In older Microsoft Windows Administrative Templates, this setting was initially named Configure Windows SmartScreen but it was renamed starting from Windows 10 Release 1703 Administrative templates
- name: "18.9.85.1.1 | Ensure 'Configure Windows Defender SmartScreen' is set to 'Enabled: Warn and prevent bypass'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\Windows\System
     name: "EnableSmartScreen"
     data: "1"
     type: dword
  tags: ['configuration']
- name: "18.9.85.1.1 | Ensure 'Configure Windows Defender SmartScreen' is set to 'Enabled: Warn and prevent bypass'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\Windows\System
     name: "ShellSmartScreen"
     data: "1"
     type: dword
  tags: ['configuration']

# Windows Defender SmartScreen - Microsoft Edge
- name: "CIS,18.9.85.2.1 | Ensure 'Configure Windows Defender SmartScreen' is set to 'Enabled'"
  win_regedit:
     path: HKLM:\SOFTWARE\Policies\Microsoft\MicrosoftEdge\PhishingFilter
     name: "EnabledV9"
     data: "1"
     type: dword
  tags: ['configuration']

- name: "CIS,18.9.85.2.1 | Ensure 'Prevent bypassing Windows Defender SmartScreen prompts for sites' is set to 'Enabled'"
  win_regedit:
     path: HKLM:\SOFTWARE\Policies\Microsoft\MicrosoftEdge\PhishingFilter
     name: "PreventOverride"
     data: "1"
     type: dword
  tags: ['configuration']

# Windows Powershell

# Enabling PowerShell script block logging will record detailed information from the processing of PowerShell commands and scripts
# Be careful with this setting, there is a potential risk of capturing credentials and other sensitive information; for this exists the feature "Protected Event Logging" to better secure event logs
- name: "CIS,18.9.100.1 | Ensure 'Turn on PowerShell Script Block Logging' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging
    name: "EnableScriptBlockLogging"
    data: "1" # Enabled
    type: dword
  tags: ['configuration']

# Transcription creates a unique record of every PowerShell session, including all input and output, exactly as it appears in the session
# It lets you capture the input and output of Windows PowerShell commands into text-based transcripts
# If this setting is enabled, there's a risk that passwords and other sensitive data could get stored in plan text in the corresponding output file
- name: "CIS,18.9.100.2 | Ensure 'Turn on PowerShell Transcription' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\Transcription
    name: "EnableTranscripting"
    data: "0" # Disabled
    type: dword
  tags: ['configuration']

# WINDOWS REMOTE SHELL

# This is an L2 policy (High Security/Sensitive Data Environment (limited functionality))
# This control will have to be set to Enabled (1) to allow for continued remote management via Ansible following machine restart
# Otherwise, the recommended value for this setting is 'Disabled'
- name: "CIS,18.9.103.1,CCE-36499-2 | Ensure 'Allow Remote Shell Access' is set to 'Disabled'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\Windows\Winrm\Service\Winrs
     name: "AllowRemoteShellAccess"
     #data: "0"
     data: "1"
     type: dword
  tags: ['configuration']

# Manage end user experience
# As cited in the CIS Microsoft Windows 10 Enterprise Benchmark, "Organizations that utilize a 3rd-party solution for patching may choose to exempt themselves from this recommendation, and instead configure it to Disabled so that the native Windows Update mechanism does not interfere with the 3rd-party patching process"
# The default value for the suboption of this setting is '3 - Auto download and notify for install'
# CIS recommends to set this to '4 - Auto download and schedule the install' if feasible, which may require additional schedule settings
- name: "CIS,18.9.108.2.1 | Ensure 'Configure Automatic Updates' is set to 'Enabled'"
  block:
    - name: Allow automatic updates
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: "NoAutoUpdate"
        data: "0" # 0 - Enabled
        type: dword
    - name: Set automatic update option
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: "AUOptions"
        data: "3" # 3 - Auto download and notify for install - The default option
        # data: "4" # 4 - Auto download and schedule the install - Enable this if your organization agrees, as this is the option CIS encourages if feasible
        type: dword
  tags: ['configuration']

# This setting is only applicable if 4 - Auto download and schedule the install is selected in recommendation 'Configure Automatic Updates'. It will have no impact if any other option is selected
- name: "CIS,18.9.108.2.2 | Ensure 'Configure Automatic Updates: Scheduled install day' is set to '0 - Every day'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
     name: "ScheduledInstallDay"
     data: "0" # 0 - Every day
     type: dword
  tags: ['configuration']

# System administrators should control when updates are applied to systems, so normal users will not be able to select the "Pause updates" option in Windows Update to prevent updates from being installed on a system
# By default, though, it is set to 'Disabled', so users have access to the "Pause updates" feature
- name: "CIS,18.9.108.2.3 | Ensure 'Remove access to “Pause updates” feature' is set to 'Enabled'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate
     name: "SetDisablePauseUXAccess"
     data: "1" # Enabled
     type: dword
  tags: ['configuration']
