---
# SYSTEM SERVICES

- name: "CIS,5.4 | Ensure 'Downloaded Maps Manager (MapsBroker)' is set to 'Disabled'"
  win_regedit:
     path: HKLM:\System\CurrentControlSet\Services\MapsBroker
     name: "start"
     data: "4" # Disabled
     type: dword
  when: (l2_environment|default(False) == True)
  tags: ['configuration']

# An exception should be made to this recommendation if intending to use Microsoft Defender Application Guard
# If it's disabled (as recommended), it won't appear in the CLARA analysis
- name: "CIS,5.8 | Ensure 'Internet Connection Sharing (ICS) (SharedAccess)' is set to 'Disabled'"
  win_regedit:
     path: HKLM:\System\CurrentControlSet\Services\SharedAccess
     name: "start"
     data: "4" # Disabled
     type: dword
  tags: ['configuration']

- name: "CIS,5.34 | Ensure 'Windows Error Reporting Service (WerSvc)' is set to 'Disabled'"
  win_regedit:
     path: HKLM:\System\CurrentControlSet\Services\WerSvc
     name: "start"
     data: "4" # Disabled
     type: dword
  when: (l2_environment|default(False) == True)
  tags: ['configuration']

# If it's disabled (as recommended), it won't appear in the CLARA analysis
- name: "CIS,5.36 | Ensure 'Windows Media Player Network Sharing Service (WMPNetworkSvc)' is set to 'Disabled' or 'Not Installed'"
  win_regedit:
     path: HKLM:\System\CurrentControlSet\Services\WMPNetworkSvc
     name: "start"
     data: "4" # Disabled
     type: dword
  tags: ['configuration']

# If it's disabled (as recommended), it won't appear in the CLARA analysis
- name: "CIS,5.37 | Ensure 'Windows Mobile Hotspot Service (icssvc)' is set to 'Disabled'"
  win_regedit:
     path: HKLM:\System\CurrentControlSet\Services\icssvc
     name: "start"
     data: "4" # Disabled
     type: dword
  tags: ['configuration']

- name: "CIS,5.40 | Ensure 'Windows Remote Management (WS-Management) (WinRM)' is set"
  win_regedit:
     path: HKLM:\System\CurrentControlSet\Services\WinRM
     name: "start"
     data: "2" # Auto, the default value
     #data: "3" # Manual but complies with CLARA's analysis
     type: dword
  tags: ['configuration']
  
# Beware when enabling this setting, as many remote administration tools, such as System Center Configuration Manager (SCCM), may require the WinRM service to be operational for remote management
- name: "CIS,5.40 | Ensure 'Windows Remote Management (WS-Management) (WinRM)' is set to 'Disabled'"
  win_regedit:
     path: HKLM:\System\CurrentControlSet\Services\WinRM
     name: "start"
     data: "4" # Disabled
     type: dword
  when: (l2_environment|default(False) == True)
  tags: ['configuration']

# XBOX
# If it's disabled (as recommended), it won't appear in the CLARA analysis
- name: "CIS,5.42 | Ensure 'Xbox Accessory Management Service (XboxGipSvc)' is set to 'Disabled'"
  win_regedit:
     path: HKLM:\System\CurrentControlSet\Services\XboxGipSvc
     name: "start"
     data: "4" # Disabled
     type: dword
  tags: ['configuration']

# If it's disabled (as recommended), it won't appear in the CLARA analysis
- name: "CIS,5.43 | Ensure 'Xbox Live Auth Manager (XblAuthManager)' is set to 'Disabled'"
  win_regedit:
     path: HKLM:\System\CurrentControlSet\Services\XblAuthManager
     name: "start"
     data: "4" # Disabled
     type: dword
  tags: ['configuration']

# If it's disabled (as recommended), it won't appear in the CLARA analysis
- name: "CIS,5.44 | Ensure 'Xbox Live Game Save (XblGameSave)' is set to 'Disabled'"
  win_regedit:
     path: HKLM:\System\CurrentControlSet\Services\XblGameSave
     name: "start"
     data: "4" # Disabled
     type: dword
  tags: ['configuration']

# If it's disabled (as recommended), it won't appear in the CLARA analysis
- name: "CIS,5.45 | Ensure 'Xbox Live Networking Service (XboxNetApiSvc)' is set to 'Disabled'"
  win_regedit:
     path: HKLM:\System\CurrentControlSet\Services\XboxNetApiSvc
     name: "start"
     data: "4" # Disabled
     type: dword
  tags: ['configuration']
