---
# DOMAIN PROFILE

- name: "CIS,9.1.1,CCE-36062-8 | Ensure 'Windows Firewall: Domain: Firewall state' is set to 'On (recommended)'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile
     name: "EnableFirewall"
     data: "1" # Enabled
     type: dword
  tags: ['configuration']

# Determines the behavior for inbound connections that do not match an inbound firewall rule
# If set to 0, this control will allow for continued remote management of the node following machine restart
# This setting, however, is already set to 'Enabled' by default
- name: "CIS,9.1.2,CCE-38117-8 | Ensure 'Windows Firewall: Domain: Inbound connections' is set to 'Block (default)'" 
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile
     name: "DefaultInboundAction"
     #data: "1" # Enabled
     data: "0"
     type: dword
  tags: ['configuration']

# Determines the behavior for outbound connections that do not match an outbound firewall rule
- name: "CIS,9.1.3,CCE-36146-9 | Ensure 'Windows Firewall: Domain: Outbound connections' is set to 'Allow (default)'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile
     name: "DefaultOutboundAction"
     data: "0" # Allowed
     type: dword
  tags: ['configuration']

# When the Apply local firewall rules setting is configured to 'No', it's recommended to also configure this setting to 'No' to avoid displaying messages to the users asking them if they want to unblock the connection
# By default, notifications will be displayed ('Yes')
- name: "CIS,9.1.4,CCE-38041-0 | Ensure 'Windows Firewall: Domain: Settings: Display a notification' is set to 'No'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile
     name: "DisableNotifications"
     data: "1" # Enabled
     type: dword
  tags: ['configuration']

- name: "CIS,9.1.5,CCE-37482-7 | Ensure 'Windows Firewall: Domain: Logging: Name' is set to '%SYSTEMROOT%\\System32\\logfiles\\firewall\\domainfw.log'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile\Logging
     name: "LogFilePath"
     data: "%SYSTEMROOT%\\System32\\logfiles\\firewall\\domainfw.log"
     type: string
  tags: ['configuration']

# By default, the value of this setting is 4,096 KB, set it to the size you consider adequate for your needs that complies to the benchmark
- name: "CIS,9.1.6,CCE-36088-3 | Ensure 'Windows Firewall: Domain: Logging: Size limit (KB)' is set to '16,384 KB or greater'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile\Logging
     name: "LogFileSize"
     data: '{{ firewallloggingsize }}'
     type: dword
  tags: ['configuration']

# By default, information about dropped packets will not be recorded in the firewall log file ('No')
- name: "CIS,9.1.7,CCE-37523-8 | Ensure 'Windows Firewall: Domain: Logging: Log dropped packets' is set to 'Yes'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile\Logging
     name: "LogDroppedPackets"
     data: "1"
     type: dword
  tags: ['configuration']

# By default, information about successful connections will not be recorded in the firewall log file ('No')
- name: "CIS,9.1.8,CCE-36393-7 | Ensure 'Windows Firewall: Domain: Logging: Log successful connections' is set to 'Yes'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile\Logging
     name: "LogSuccessfulConnections"
     data: "1" # Enabled
     type: dword
  tags: ['configuration']

# PRIVATE PROFILE

- name: "CIS,9.2.1,CCE-38239-0 | Ensure 'Windows Firewall: Private: Firewall state' is set to 'On (recommended)'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile
     name: "EnableFirewall"
     data: "1"
     type: dword
  tags: ['configuration']

- name: "CIS,9.2.2,CCE-38042-8 | Ensure 'Windows Firewall: Private: Inbound connections' is set to 'Block (default)'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile
     name: "DefaultInboundAction"
     data: "1"
     type: dword
  tags: ['configuration']

- name: "CIS,9.2.3,CCE-38332-3 | Ensure 'Windows Firewall: Private: Outbound connections' is set to 'Allow (default)'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile
     name: "DefaultOutboundAction"
     data: "0"
     type: dword
  tags: ['configuration']

- name: "CIS,9.2.4,CCE-37621-0 | Ensure 'Windows Firewall: Private: Settings: Display a notification' is set to 'No'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile
     name: "DisableNotifications"
     data: "1"
     type: dword
  tags: ['configuration']

- name: "CIS,9.2.5,CCE-37569-1 | Ensure 'Windows Firewall: Private: Logging: Name' is set to '%SYSTEMROOT%\\System32\\logfiles\\firewall\\privatefw.log'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile\Logging
     name: "LogFilePath"
     data: "%SYSTEMROOT%\\System32\\logfiles\\firewall\\privatefw.log"
     type: string
  tags: ['configuration']

- name: "CIS,9.2.6,CCE-38178-0 | Ensure 'Windows Firewall: Private: Logging: Size limit (KB)' is set to '16,384 KB or greater'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile\Logging
     name: "LogFileSize"
     data: '{{ firewallloggingsize }}'
     type: dword
  tags: ['configuration']

- name: "CIS,9.2.7,CCE-35972-9 | Ensure 'Windows Firewall: Private: Logging: Log dropped packets' is set to 'Yes'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile\Logging
     name: "LogDroppedPackets"
     data: "1"
     type: dword
  tags: ['configuration']

- name: "CIS,9.2.8,CCE-37387-8 | Ensure 'Windows Firewall: Private: Logging: Log successful connections' is set to 'Yes'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile\Logging
     name: "LogSuccessfulConnections"
     data: "1"
     type: dword
  tags: ['configuration']

# PUBLIC PROFILE

- name: "CIS,9.3.1,CCE-37862-0 | Ensure 'Windows Firewall: Public: Firewall state' is set to 'On (recommended)'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile
     name: "EnableFirewall"
     data: "1" # Enabled
     type: dword
  tags: ['configuration']

# If this control is set to Disabled (0), it will allow for continued remote management of the node following machine restart
- name: "CIS,9.3.2,CCE-36057-8 | Ensure 'Windows Firewall: Public: Inbound connections' is set to 'Block (default)'"
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile
    name: "DefaultInboundAction"
    #data: "1" # Enabled
    data: "0"
    type: dword
  tags: ['configuration']

- name: "CIS,9.3.3,CCE-37434-8 | Ensure 'Windows Firewall: Public: Outbound connections' is set to 'Allow (default)'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile
     name: "DefaultOutboundAction"
     data: "0"
     type: dword
  tags: ['configuration']

- name: "CIS,9.3.4,CCE-38043-6 | Ensure 'Windows Firewall: Public: Settings: Display a notification' is set to 'No'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile
     name: "DisableNotifications"
     data: "1"
     type: dword
  tags: ['configuration']

- name: "CIS,9.3.5,CCE-37861-2 | Ensure 'Windows Firewall: Public: Settings: Apply local firewall rules' is set to 'No'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile
     name: "AllowLocalPolicyMerge"
     data: "0"
     type: dword
  tags: ['configuration']

- name: "CIS,9.3.6,CCE-36268-1 | Ensure 'Windows Firewall: Public: Settings: Apply local connection security rules' is set to 'No'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile
     name: "AllowLocalIPsecPolicyMerge"
     data: "0"
     type: dword
  tags: ['configuration']

- name: "CIS,9.3.7,CCE-37266-4 | Ensure 'Windows Firewall: Public: Logging: Name' is set to '%SYSTEMROOT%\\System32\\logfiles\\firewall\\publicfw.log'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile\Logging
     name: "LogFilePath"
     data: "%SYSTEMROOT%\\System32\\logfiles\\firewall\\publicfw.log"
     type: string
  tags: ['configuration']

- name: "CIS,9.3.8,CCE-36395-2 | Ensure 'Windows Firewall: Public: Logging: Size limit (KB)' is set to '16,384 KB or greater'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile\Logging
     name: "LogFileSize"
     data: '{{ firewallloggingsize }}'
     type: dword
  tags: ['configuration']

- name: "CIS,9.3.9,CCE-37265-6 | Ensure 'Windows Firewall: Public: Logging: Log dropped packets' is set to 'Yes'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile\Logging
     name: "LogDroppedPackets"
     data: "1"
     type: dword
  tags: ['configuration']

- name: "CIS,9.3.10,CCE-36394-5 | Ensure 'Windows Firewall: Public: Logging: Log successful connections' is set to 'Yes'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile\Logging
     name: "LogSuccessfulConnections"
     data: "1"
     type: dword
  tags: ['configuration']