---
# Showing a warning message prior to login of ordinary users could assist in the prosecution of trespassers on the computer system.
# Also, changing some of these login banners may have as a side effect hiding important OS version and other detailed system information from attackers attempting to target specific exploits at a system
# This setting is subject to your organization's legal counsel reviewing the content of all messages before any system modifications are made
# The MOTD should be in line with your organization's/site's policy
- name: CIS, 1.7.1 - Ensure message of the day is configured properly
  block:
    - name: Disable some default motd messages
      file: 
        path: '{{ motd_folder }}/{{ item }}'
        state: file
        mode: '0644'
      loop:
        - 91-release-upgrade
        - 10-help-text
        - 50-motd-news
        - 92-unattended-upgrades
    - name: Custom motd messages
      copy:
        src: '../conf/motd'
        dest: '/etc/motd'
        mode: '0640'
        owner: 'root'
        group: 'root'
  tags: ['configuration']

# If the motd is not used, this file can be removed.
- name: Remove motd
  command: rm /etc/motd
  when: (remove_motd|default(False) == True)
