---
# UNCOMMON NETWORK PROTOCOLS
# This task includes the following CIS recommendations:
# CIS, 3.4.1 - Ensure DCCP is disabled -> Be careful, as this is has a profile applicability of L2 for both workstations and servers
# CIS, 3.4.2 - Ensure SCTP is disabled -> Be careful, as this is has a profile applicability of L2 for both workstations and servers
# CIS, 3.4.3 - Ensure RDS is disabled -> Be careful, as this is has a profile applicability of L2 for both workstations and servers
# CIS, 3.4.4 - Ensure TIPC is disabled -> Be careful, as this is has a profile applicability of L2 for both workstations and servers
- name: Restrict uncommon network protocolos
  lineinfile:
    create: true
    dest: '/etc/modprobe.d/{{ item }}.conf'
    regexp: '{{  item }}'
    line: 'install {{ item }} /bin/true'
  loop:
    - dccp
    - sctp
    - rds
    - tipc
  tags: ['configuration']
