---
- name: Make sure that software required by CIS standard is present
  apt:
    name: '{{ packages_present }}'
    state: present
    update_cache: yes
  when:
    - ansible_facts['os_family']|lower == "debian"
  tags: ['install']

- name: Install and enable systemd-timesyncd 
  block: 
    - name: Ensure systemd-timesyncd is installed
      package:
        name: systemd-timesyncd
        state: present

    - name: Gather the package facts
      package_facts:
        manager: auto

    - name: Enable service systemd-timesyncd
      service:
        name: systemd-timesyncd
        enabled: 'yes'
        state: started
        masked: 'no'
      when:
        - '"systemd-timesyncd" in ansible_facts.packages'
  tags: ['install']

- name: Filesystem integrity checking policies (make sure AIDE is installed)
  include_tasks: filesystem_integrity_checking.yml
  when: (aide_required|default(False) == True)
  tags: ['install']

- name: Make sure that software prohibited by CIS standard is absent
  apt:
    name: '{{ packages_absent }}'
    state: absent
    update_cache: yes
  when:
    - ansible_facts['os_family']|lower == "debian"
  tags: ['install']

