---
- name: CIS, 2.1.1.2 - Ensure systemd-timesyncd is configured
  copy:
    src: ../conf/systemd-timesyncd.service
    dest: /lib/systemd/system/systemd-timesyncd.service
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify: reload_systemd
  tags: ['configuration']
