---
- name: "CIS,19.1.3.1,CCE-37970-1 | Ensure 'Enable screen saver' is set to 'Enabled'"
  win_regedit:
     path: HKU:\.DEFAULT\Software\Policies\Microsoft\Windows\Control Panel\Desktop
     name: "ScreenSaveActive"
     data: "{{ (screensaver_enabled|default(True) == True ) | ternary('1', '0') }}"
     type: string
  tags: ['configuration']

- name: "CIS,19.1.3.1,CCE-37970-1 | Ensure 'Enable screen saver' is set to 'Enabled'"
  win_regedit:
     path: HKCU:\Software\Policies\Microsoft\Windows\Control Panel\Desktop
     name: "ScreenSaveActive"
     data: "{{ (screensaver_enabled|default(True) == True ) | ternary('1', '0') }}"
     type: string
  tags: ['configuration']

- name: "CIS,19.1.3.2,CCE-37658-2 | Ensure 'Password protect the screen saver' is set to 'Enabled'"
  win_regedit:
     path: HKCU:\Software\Policies\Microsoft\Windows\Control Panel\Desktop
     name: "ScreenSaverIsSecure"
     data: "{{ (screensaver_enabled|default(True) == True ) | ternary('1', '0') }}"
     type: string
  when: > 
      (screensaver_enabled|default(True) == True)
  tags: ['configuration']

- name: "CIS,19.1.3.3,CCE-37908-1 | Ensure 'Screen saver timeout' is set to 'Enabled: 900 seconds or fewer, but not 0'"
  win_regedit:
     path: HKU:\.DEFAULT\Software\Policies\Microsoft\Windows\Control Panel\Desktop
     name: "ScreenSaveTimeOut"
     data: "900"
     type: string
  when: >
      (screensaver_enabled|default(True) == True)
  tags: ['configuration']

- name: "CIS,19.1.3.3,CCE-37908-1 | Ensure 'Screen saver timeout' is set to 'Enabled: 900 seconds or fewer, but not 0'"
  win_regedit:
     path: HKCU:\Software\Policies\Microsoft\Windows\Control Panel\Desktop
     name: "ScreenSaveTimeOut"
     data: "900"
     type: string
  when: >
      (screensaver_enabled|default(True) == True)
  tags: ['configuration']
